version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: mypass
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 15s
      timeout: 15s
      retries: 20
    ports:
      - 3366:3306
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8080:8000
    volumes:
      - /var/www/vendor
    depends_on:
      mysql: 
        condition: service_healthy
    networks:
      - app_network
  frontend:
    build:
       context: ./frontend
       dockerfile: Dockerfile
    container_name: frontend
    environment:
      VITE_API_URL: http://localhost:8080/api/v1/
    ports:
      - 9000:9000
    volumes:
      - /var/www/node_modules
    networks:
      - app_network
volumes:
  mysql_data:
networks:
  app_network:
    driver: bridge